topaz: parts: remove prox check
YAAP doesn't have this commit: https://github.com/LineageOS/android_frameworks_base/commit/1478727fd9c10385c86eb7ff0cbea796292bb889
so this will fail. Remove it for now since I can't figure out how to merge LOS' commit to YAAP and adapt

device/xiaomi/raphael/parts/src/org/lineageos/settings/doze/PickupSensor.java:76: error: cannot find symbol
                mPowerManager.wakeUpWithProximityCheck(SystemClock.uptimeMillis(),
                             ^
  symbol:   method wakeUpWithProximityCheck(long,int,String)
  location: variable mPowerManager of type PowerManager